import {
  scriptedData1,
  scriptedData2,
  scriptedData3,
} from "./scriptedChartData";

export const configLine = {
  chart: "Line",
  chartConfig: {
    data: scriptedData1,
    colors: ["#C52083"],
    width: 900,
    height: 400,
    margin: { top: 20, right: 20, bottom: 60, left: 80 },
    xScale: {
      type: "time",
      format: "%Y",
      useUTC: false,
      precision: "year",
    },
    xFormat: "time:%Y",
    yScale: {
      type: "linear",
      stacked: false,
    },
    axisLeft: {
      legend: "linear scale",
      legendOffset: 0,
    },
    axisBottom: {
      format: "%b %d",
      tickValues: "every 2 years",
      legend: "time scale",
      legendOffset: 0,
    },
    useMesh: true,
    enableSlices: false,
    iceTitle: "Capital Expenditure Forecast",
  },
  onClick: _.noop,
  scriptedData: { data: scriptedData1 },
};

export const configDonut = {
  chart: "Donut",
  chartConfig: {
    data: scriptedData2,
    useMesh: true,
    enableSlices: false,
    margin: { top: 40, right: 80, bottom: 80, left: 80 },
    innerRadius: "0.5",
    padAngle: "0.7",
    cornerRadius: "3",
    activeOuterRadiusOffset: "8",
    borderWidth: "1",
    borderColor: {
      from: "color",
      modifiers: [["darker", "0.2"]],
    },
    arcLinkLabelsSkipAngle: "10",
    arcLinkLabelsTextColor: "#333333",
    arcLinkLabelsThickness: "2",
    arcLinkLabelsColor: { from: "color" },
    arcLabelsSkipAngle: "10",
    arcLabelsTextColor: {
      from: "color",
      modifiers: [["darker", "2"]],
    },
    defs: [
      {
        id: "dots",
        type: "patternDots",
        background: "inherit",
        color: "rgba(255, 255, 255, 0.3)",
        size: "4",
        padding: "1",
        stagger: "true",
      },
      {
        id: "lines",
        type: "patternLines",
        background: "inherit",
        color: "rgba(255, 255, 255, 0.3)",
        rotation: "-45",
        lineWidth: "6",
        spacing: "10",
      },
    ],
    fill: [
      { match: { id: "ruby" }, id: "dots" },
      { match: { id: "c" }, id: "dots" },
      { match: { id: "go" }, id: "dots" },
      { match: { id: "python" }, id: "dots" },
      { match: { id: "scala" }, id: "lines" },
      { match: { id: "lisp" }, id: "lines" },
      { match: { id: "elixir" }, id: "lines" },
      { match: { id: "javascript" }, id: "lines" },
    ],
    iceTitle: "Capital Expenditure Forecast",
  },
  onClick: _.noop,
  scriptedData: { data: scriptedData2 },
};

export const configBar = {
  chart: "Bar",
  chartConfig: {
    data: scriptedData3,
    keys: ["hot dog", "burger", "sandwich", "kebab", "fries", "donut"],
    indexBy: "country",
    margin: { top: 50, right: 130, bottom: 50, left: 60 },
    padding: "0.3",
    valueScale: { type: "linear" },
    indexScale: { type: "band", round: "true" },
    colors: { scheme: "nivo" },
    defs: [
      {
        id: "dots",
        type: "patternDots",
        background: "inherit",
        color: "#38bcb2",
        size: 4,
        padding: 1,
        stagger: "true",
      },
      {
        id: "lines",
        type: "patternLines",
        background: "inherit",
        color: "#eed312",
        rotation: "-45",
        lineWidth: 6,
        spacing: 10,
      },
    ],
    fill: [
      { match: { id: "fries" }, id: "dots" },
      { match: { id: "sandwich" }, id: "lines" },
    ],
    borderColor: {
      from: "color",
      modifiers: [["darker", "1.6"]],
    },
    axisTop: "null",
    axisRight: "null",
    axisBottom: {
      tickSize: 5,
      tickPadding: 5,
      tickRotation: 0,
      legend: "country",
      legendPosition: "middle",
      legendOffset: 32,
      truncateTickAt: 0,
    },
    axisLeft: {
      tickSize: 5,
      tickPadding: 5,
      tickRotation: 0,
      legend: "food",
      legendPosition: "middle",
      legendOffset: "-40",
      truncateTickAt: 0,
    },
    labelSkipWidth: "12",
    labelSkipHeight: "12",
    labelTextColor: {
      from: "color",
      modifiers: [["darker", "1.6"]],
    },
    role: "application",
    ariaLabel: "Nivo bar chart demo",
    barAriaLabel: 'e=>e.id+": "+e.formattedValue+" in country: "+e.indexValue',
    iceTitle: "Capital Expenditure Forecast",
  },
  onClick: _.noop,
  scriptedData: { data: scriptedData3 },
};
